// <auto-generated />
using System;
using Banking.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace Banking.Migrations
{
    [DbContext(typeof(MyContext))]
    [Migration("20190916144102_third")]
    partial class third
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.2.4-servicing-10062")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("Banking.Models.Account", b =>
                {
                    b.Property<int>("AID")
                        .ValueGeneratedOnAdd();

                    b.Property<double>("Balance");

                    b.Property<DateTime>("CreatedAt");

                    b.Property<string>("Email")
                        .IsRequired();

                    b.Property<string>("FirstName")
                        .IsRequired();

                    b.Property<string>("LastName")
                        .IsRequired();

                    b.Property<string>("Password")
                        .IsRequired();

                    b.Property<DateTime>("UpdatedAt");

                    b.HasKey("AID");

                    b.ToTable("Accounts");
                });

            modelBuilder.Entity("Banking.Models.Log", b =>
                {
                    b.Property<int>("LID")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Email")
                        .IsRequired();

                    b.Property<string>("Password")
                        .IsRequired();

                    b.HasKey("LID");

                    b.ToTable("Logins");
                });

            modelBuilder.Entity("Banking.Models.Transaction", b =>
                {
                    b.Property<int>("TID")
                        .ValueGeneratedOnAdd();

                    b.Property<int>("AID");

                    b.Property<double>("Amount");

                    b.Property<DateTime>("CreatedAt");

                    b.HasKey("TID");

                    b.HasIndex("AID");

                    b.ToTable("Trans");
                });

            modelBuilder.Entity("Banking.Models.Transaction", b =>
                {
                    b.HasOne("Banking.Models.Account", "Trans")
                        .WithMany("Trans")
                        .HasForeignKey("AID")
                        .OnDelete(DeleteBehavior.Cascade);
                });
#pragma warning restore 612, 618
        }
    }
}
